Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,6 +24,13 @@ jobs:
     - name: List files in the root directory
       run: ls -alh
 
+    - name: Check if requirements.txt exists
+      run: |
+        if [ ! -f requirements.txt ]; then
+          echo "ERROR: requirements.txt does not exist."
+          exit 1
+        fi
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
@@ -46,6 +53,13 @@ jobs:
       uses: actions/setup-python@v2
       with:
         python-version: '3.9'
+
+    - name: Check if requirements.txt exists (for deployment)
+      run: |
+        if [ ! -f requirements.txt ]; then
+          echo "ERROR: requirements.txt does not exist."
+          exit 1
+        fi
 
     - name: Install dependencies (for deployment)
       run: |
